# Generated by Django 4.2.15 on 2024-08-14 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Budget_Manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
